version: "2"

run:
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - unused

formatters:
  enable:
    - gofmt
    - goimports
